updated strings in DynamicRadio_BE.txt
PlagaMedicum/ProjectZomboidTranslations pull request #2
Opened 2023-01-07 12:54 UTC by sansergeich

Паспрабаваў перакласці застаўшуюся частку файлу DynamicRadio_BE.txt.
Файл ужо ў кадзіроўцы UTF-8, канфліктаў з папярэднім наборам зменаў быць не павінна.

2023-01-10 15:15 UTC, PlagaMedicum requested changes
Адкаменціў свае заўвагі да перакладу.
Калі што, магу даць доступ да сваіх напрацовак па гласарыі + раю карыстацца verbum.by з арыентацыяй на слоўнік Сушы ў першую чаргу. Пашкевіч адносна нядрэнны, але ўсё ж тарашкевіца, таму акуратна з ім.

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_13 = "<бззт>... сказаў, што яны прыйшлі са ўсходу <фззт> паўтараю: усходу... <вззт>",
«bzzt», «fzzt» і інш — гэта гукаперайманні. У беларускай мове ёсць свае прынцыпы гукапераймання, якія адрозніваюцца ад ангельскай традыцыі.  Мы не кажам «т» на канцы, калі пераймаем гукі жужжання, трашчання і г.д. Таксама, звычайна пры запісу мы шырока выкарыстоўваем працяжнікі: «му-у-у», «тпр-р-р», «ж-ж-ж».

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_weather_0_b = "Надвор'е будзе трывацца ў працягу дня... ",
цягам дня

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_weather_0_c = "Надвор'е скончыцца %s... ",
Тут перыяд надвор’я. Надвор’е агулам не можа скончыцца

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_Power_1 = "Электрасеці Кнокс: Выяўлуны ваганні магутнасці.",
- Акругу транслітаруем як «Нокс»
- Power grid = Энергасістэма або электрасетка
- Вызначаны ваганні энергіі. — не ўпэўнены, што слова «магутнасць» тут будзе прыдатна ўжываць

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_Power_2 = "Электрасеці Кнокс: Збой сістэмы. Сетка узламана.",
лепей сказаць «сетка скампраментавана», бо не абавязкова, што яе прам узламалі.

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_weather_snowfall = " магчымы снегапад.",
з магчымасцю — могуць быць кампінацыі тыпу thunderstorm with a chance of snowfall

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_weather_warning = "Папярэджанне аб цяжкім надвор'і. %s непазбежна. Разліковы час надыходжання %s дзён...",
Праблемы з родам. Трэба перанесці формы слова «непазбежны» у кожны варыянт: «Навальніца непазбежна», «Трапічны шторм непазбежны».
Тады застаецца «%s. Разліковы час %s д...»

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_0 = "Усяму асабістаму складу. Часовы збой сувязі для %s сектараў зоны адчужэння %i, %i, %i і %i",
для зоны адчужэння %s... Сектары %i, %i, %i і %i

Так разумею, што %s — гэта назва зоны

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_0 = "Усяму асабістаму складу. Часовы збой сувязі для %s сектараў зоны адчужэння %i, %i, %i і %i",
Усяму асабоваму складу або Усяму персаналу

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_7 = "<бззт>..ЯНЫ ПРАРВАЛІСЯ!... <бззт> Д'ЯБЛ! СТРЫМЛІВАЙЦЕ ІХ! НАМ ПАТРЭБНА ПАДТ... <вззт>",
Д’ябал

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_9 = "<бззт>... уцёкшыя... <фззт> рухаюцца ...<вззт>",
удалося ўцячы, перасоўванне да

нельга казаць аб колькасці тут

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_10 = "<бззт>... Аперацыя Артэміда <фззт> вышэйшы прыярытэт ...<вззт>",
найвышэйшы

2023-01-10 15:15 UTC, PlagaMedicum commented on BE/DynamicRadio_BE.txt
> +    AEBS_random_11 = "<бззт>... хто адпраўляе іх? <фззт> Я разумаю, мы атрымалі загады, але... <вззт>",
разумею

2023-01-12 19:09 UTC, sansergeich commented on BE/DynamicRadio_BE.txt
> +    AEBS_Power_1 = "Электрасеці Кнокс: Выяўлуны ваганні магутнасці.",
Мне здаецца, што ў кантэксце электрасетак якраз больш каррэктна выкарыстоўваць тэрмін "магутнасць", альбо магчыма, "напружанне". "Энэргія" тут не вельмі стасуе, яна можа быць спажыта, але ня можа вагацца. А вось здольнасць электрасеткі даваць энэргію можа быть ахарактэрызавана тэрмінамі "магутнасць" і "напружанне" і гэтая здольнась можа вагацца ў залежнасці ад стану сеткі.

2023-01-12 19:11 UTC, sansergeich commented
Дзякуй за заўвагі. Каміт з выпраўленнямі на галінцы. 

Які падыход да вырашэння канфлікту?

2023-01-23 23:14 UTC, PlagaMedicum commented
паспрабуем так, калі будуць праблемы з кадзіроўкай — рашу

2023-01-23 23:14 UTC, merged